evil-morfar/RCLootCouncil2

- Modules/lootHistory.lua
I've modified the EQ DKP Plus XML Export to include some additional fields that the EQ DKP Plus CMS requires to import successfully.
Some of the data is kind of dummy data... the member join time is always the earliest raid start time, and the leave time is always the latest raid join time + 26000.
> EQDKP Plus Export tweaks

- Modules/votingFrame.lua
This typo is making AWARD_FOR button unusable, or award to the wrong person, or award to not existing person, because it is accessing the global variable ```name```.
> Fix typo in the AWARD_FOR button of the rightclick menu

- ml_core.lua
```RCLootCouncilML:UpdateGroup(ask)``` sometimes gives nil error on login.
This is due to ```GetRaidRosterInfo(i), 1<=i<=GetNumGroupMembers()``` can return nil when group information is not ready. We should abort and retry ```ML:UpdateGroup``` when we detect it.
Error Messages:
```
3x RCLootCouncil\core.lua:1605: bad argument #1 to 'gsub' (string expected, got nil)
[C]: in function `gsub'
RCLootCouncil\core.lua:1605: in function `UnitName'
RCLootCouncil\ml_core.lua:114: in function `UpdateGroup'
RCLootCouncil\ml_core.lua:279: in function `NewML'
RCLootCouncil\core.lua:1289: in function `NewMLCheck'
RCLootCouncil\core.lua:1223: in function `?'
...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:147: in function <...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string …
```
> Fix nil error on login caused by GetRaidRosterInfo(i) returns nil

- core.lua
Item 151967 is not in game yet in patch 7.3.2. This item causes me to stuck in the session frame.
> Item 151967 is not in game in Patch 7.3.2

- Modules/votingFrame.lua
- core.lua
- ml_core.lua
+ all announcement print itself when the channel is invalid. (channel is "group" when not in group. channel is "guild" when not in guild).
+ While in test mode, all announcement is prefixed by "(Test)" to avoid confusion by other people.
+ Also send award message while in test mode.
+ New API: RC:SendAnnouncement(msg, channel)
> Test announcement when solo

- Modules/lootFrame.lua
- Modules/votingFrame.lua
- core.lua
- ml_core.lua
+ The ilvl of armor token is shown as ###+ instead of ###
+ This change has been applied to voting frame, loot frame, award announcement and consideration announcement.
> The ilvl of armor token is shown as ###+ instead of ###

- Locale/enUS.lua
- Modules/votingFrame.lua
+ NEW: Reannounce all items usable by the candidate.
+ Reannounce "this item" now also includes all unawarded duplicates.
> Add Feature: Reannounce all items usable by the candidate.

- Modules/votingFrame.lua
```
122x RCLootCouncil\Modules\votingFrame.lua:342: attempt to index field '?' (a nil value)
RCLootCouncil\Modules\votingFrame.lua:342: in function <RCLootCouncil\Modules\votingFrame.lua:338>
RCLootCouncil\Modules\votingFrame.lua:397: in function `Update'
RCLootCouncil\Modules\votingFrame.lua:173: in function `?'
...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:147: in function <...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[4]"]:4: in function <[string "safecall Dispatcher[4]"]:4>
[C]: ?
[string "safecall Dispatcher[4]"]:13: in function `?'
...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:92: in function `Fire'
...faceBugSack\Libs\AceComm-3.0\AceComm-3.0-10.lua:260: in function …
```
> VotingFrame:Update() should check if loot table exists.

- Modules/lootHistory.lua
+ Fix a long standing bug that if we delete multiple entries of the same person without closing the history window, unintended entry is deleted.
+ How to reproduce:
+ Delete the earliest entry of player A.
+ Delete the latest entry of player A will cause an nil error.
+ Delete other entries of player A does not cause error and looks like the entry is deleted. However, close RC history window and reopen it shows wrong entry is deleted.
+ The reason of this bug is ```data[realrow].num``` is not updated when an entry is deleted.
> Fix bug that RCHistory deletes unintended entry.

- ml_core.lua
+ Fix a problem in announcement when response contains special characters such as %, [], ()
---
+ A lua function defined by FrameXML/ChatFrame.lua is used to fix this problem. Copy and paste here for reference.
```
local symbols = {"%%", "%*", "%+", "%-", "%?", "%(", "%)", "%[", "%]", "%$", "%^"} --% has to be escaped first or everything is ruined
local replacements = {"%%%%", "%%%*", "%%%+", "%%%-", "%%%?", "%%%(", "%%%)", "%%%[", "%%%]", "%%%$", "%%%^"}
function escapePatternSymbols(text)
for i=1, #symbols do
text = text:gsub(symbols[i], replacements[i])
end
return text
end
```
> Fix bug when response contains special characters.

- ml_core.lua
+ If ML autoStart the session, when ML loots corpse immediately after reload, because data isn't ready, session does not start, but item has been added to the lootTable. If ML closes and reopens the loot window, items in the corpse will be added multiple times to the lootTable.
+ We solve this problem by showing session frame instead of autoStart if data isn't ready.
> Fix bug when ML loots corpse immediately after reload.

- ml_core.lua
+ Send offline timer 7s after ML receives the lootTable rather than 10s after sends the lootTable
+ I don't want to see "someone1 is offline" when ML's communication channel is crowded or lootTable is big.
> Send offline timer X seconds after ML receives the lootTable rather sends the lootTable

- Modules/lootFrame.lua
- Modules/votingFrame.lua
- core.lua
- ml_core.lua
```
-- The link of same item generated from different player, or if two links are generated between player spec switch, are NOT the same
-- Because item link contains player's level and spec ID.
-- This function compares link with link level and spec ID removed.
-- Also compare with unique id removed, because wowpedia says that 
-- " In-game testing indicates that the UniqueId can change from the first loot to successive loots on the same item."
-- Although log shows item in the loot actually has no uniqueId in Legion, but just in case Blizzard changes it in the future.
function RCLootCouncil:ItemIsItem(item1, item2)
```
---
Compare item link by ==  fail if the item link is generated by different player, or by the same player after changing spec. Currently there is a bug when ML switches …
> Dont use == to compare item link

- Modules/votingFrame.lua
- core.lua
+ Manual roll should set rolls for all duplicate items. No one does two manual rolls for two instances of the same item
+ Fix a bug that non-ML council could send unnecessary roll commands if autoRolls is enabled.
+ The original roll feature also sets the same roll for duplicate items.
+ This is debatable, but if we roll on the duplicate items, we usually award the 1st item to the highest rolled candidate, 2nd item to the 2nd highest rolled candidate. I do think this makes sense.
+ The algorithm to generate random numbers is changed. Now it is guaranteed that every candidate has different roll, if the random numbers are generated by RC.
+ There was a ticket on Curseforge [#299](https://wow.curseforge.com/projects/rclootcouncil/issues/299) complaining that rolls can be the same and request …
> Duplicate items should have same roll

- core.lua
```
-- Defined in SharedXML/Util.lua:199
function FindInTableIf(tbl, pred)
for k, v in pairs(tbl) do
if (pred(v)) then
return k, v;
end
end
return nil;
end
```
I don't like to do raw comparison to the name, especially when the operation has vert bad effect if failed.
> Use FindInTableIf instead of tContains in council check

- Modules/lootHistory.lua
Although this error is definitely related to my saved variable, let's have an extra nil check.
```
1x RCLootCouncil\Modules\lootHistory.lua:343: attempt to index field '?' (a nil value)
RCLootCouncil\Modules\lootHistory.lua:343: in function <RCLootCouncil\Modules\lootHistory.lua:334>
(tail call): ?
[C]: in function `sort'
RCLootCouncil\Libs\lib-st\Core.lua:301: in function `SortData'
RCLootCouncil\Libs\lib-st\Core.lua:682: in function `?'
RCLootCouncil\Libs\lib-st\Core.lua:53: in function `FireUserEvent'
RCLootCouncil\Libs\lib-st\Core.lua:96: in function <RCLootCouncil\Libs\lib-st\Core.lua:95>
```
> Fix a nil error in response sort of loot history

- Locale/enUS.lua
- Modules/votingFrame.lua
- core.lua
+ When the item is awarded, sets the response of the awardee to "Awarded" to all duplicate items, so I don't need to remember who have been awarded one of the duplicate items, so I never mistakenly award two identical items to the same people
+ This breaks backward compatibility though
> Award sets the response to Awarded

- core.lua
It's posssible that the first return value of GetRaidRosterInfo is nil, when the 2nd return value is not nil
> Fix nil in GetML

- Modules/votingFrame.lua
If you are not going to merge #92 , then at least merge this.
This is an issue in Lib-scrollTable that one sortData does not correctly sort responses after rolls, if roll gets updated.
Use SortData twice solves the problem
> Need to use SortData() twice to correctly sort response after rolls

- ml_core.lua
+ Complete forget to edit this when localized subType is removed.
+ The sort order is the same as before the fix. (Except weapon is sorted after relic now, but there is no weapon in this expansion, so doesn't matter.)
+ This is the reason why we should clear our saved variables when testing.
> Fix loot table sorting

- core.lua
+ When receiving MLdb, we should check if it is from the ML.
+ I suspect this is the reason of the recent reports of MLdb is not being received because some non-ML enables ML module and send MLdb
+ Even if this is not the reason, we should always check it, in case someone's version messes up
+ Although you claimed long ago " NOTE: 2.1.7 - While a check for this does make sense, I'm just really tired of mldb problems, and noone should really be able to send it without being ML in the first place. So just accept it as is.", but this is really never the reason why the mldb is not received. Not checking this only creates problem when any non-ML somehow sends mldb. We should always check if the ml commands are from the ml.
+ Also clear mldb when ml changes.
+ Then, we'll only have either no …
> Attempt to fix mldb

- Modules/votingFrame.lua
There are several issues in ```IsFiltering``` function.
+ Unneeded redundent code, make it harder to expand the filter feature.
+ This function has issue when the saved variable ```db.modules["RCVotingFrame"].filters``` contains garbage. It bugged if I active the filter for a button, but later removed the button from responses..
+ Replace this function by one line solution: ```#self.frame.st.filtered < #self.frame.st.data```
+ Although it does not change the color of filter button when a filter is active but no rows are filtered, I think it does not matter.
> Remove function IsFiltering, replace it by a one-line code.

- core.lua
+ I think add default ignored items should no longer be necessary in the future.
+ RC should only loots equipable+relic+mount+tiers. We actually don't need "loot everything" option. Dont think there is any other item that can be master looted.
+ Tiers can be recognized by parsing tooltip of "Class: xxx", or using ```GetItemSpell```
+ The easier way is to check the GetMasterLootCandidate, if there is no other person except ML, dont add it to the session.
> Add sigil of the dark titan to ignoredItems

- Modules/sessionFrame.lua
+ This fixes some session frame lag, especially in test mode
> Do not make unnesssary scheduling to recreate the session frame

- core.lua
- ml_core.lua
+ The recent error report shows that it is no longer guaranteed that the info of items in loot slot is ready when the loot window opens.
+ Retry in the next frame if get any uncached item.
+ Retry in the next frame instead of 1s, because I follow Blizzard code which retries in the next frame.
```
-- FrameXML/LootFrame.lua, line 227
else
text:SetText("");
_G["LootButton"..index.."IconTexture"]:SetTexture(nil);
SetItemButtonNormalTextureVertexColor(button, 1.0, 1.0, 1.0);
LootFrame:SetScript("OnUpdate", LootFrame_OnUpdate);
button:Disable();
end
> Delay LOOT_OPENED event handling when encounter an uncached item.

- core.lua
- ml_core.lua
https://media-elerium.cursecdn.com/attachments/220/817/rclootcouncil.txt
Disconnection happens on entry 309, but the lootTable is received on entry 98.
About 200 addon messages are received within 1s.
I highly suspect the disconnection is caused by burst traffic due to the following reasons:
1. It seems only happens in large raid. More likely in 30man raid. No reports for small raid.
2. It only happens when loot frame pops up when there are lots of traffic happening.
3. Happens randomly, and does not happen for everyone. I think it is because some server is has lower data threshold than the others.
---
http://wowwiki.wikia.com/wiki/ChatThrottleLib
> The World of Warcraft servers will disconnect you if you generate too much output. This is not limited to chat output; any type of output can …
> Attempt to fix disconnection

- Utils/sync.lua
+ Thanks for the problematic RCLootCouncil:UnitName(), every time when a name is not processed by RCLootCouncil:UnitName(), something is bugged for Russian
> Fix sync for Russian

- Locale/enUS.lua
- Modules/votingFrame.lua
- core.lua
+ disabled by default
+ Double click item button to toggle.
+ Working on always show tooltip on loot frame
> Always show tooltip on voting frame

- Locale/enUS.lua
- Modules/lootFrame.lua
- core.lua
+ Very useful feature. More useful than always show tooltip on voting frame. This speed things up.
+ Always show the tooltip of the first frame
+ Double click item icon to toggle.
> Always show tooltip on loot frame

- Locale/enUS.lua
- Modules/lootFrame.lua
- Modules/sessionFrame.lua
- Modules/votingFrame.lua
- core.lua
+ The item bonus text(socket/leech/avoidance/speed/indestructible) is now shown in session frame, loot frame and the voting frame.
+ The item state text in the voting frame (green text such as "Mythic Warforged") is removed. One reason is that the item state text is too far right when item bonus is shown with the ilvl. The other reason is that item state is not sth really needed. Everyone can know whether an item is warforged/titanforged according to its ilvl.
+ I have used this PR as ML for two weeks without a problem.
> Show item bonus text
